# DO NOT EDIT THIS FILE!
#
# Python module ShoppingCartApp__POA generated by omniidl

import omniORB
omniORB.updateModule("ShoppingCartApp__POA")

# ** 1. Stub files contributing to this module
import ShoppingCart_idl

# ** 2. Sub-modules

# ** 3. End
