package ShoppingCartApp;


/**
* ShoppingCartApp/_ShoppingCartStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

public class _ShoppingCartStub extends org.omg.CORBA.portable.ObjectImpl implements ShoppingCartApp.ShoppingCart
{

  public void getShoppingCartContents (ShoppingCartApp.cartContentsHolder contents)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getShoppingCartContents", true);
                $in = _invoke ($out);
                contents.value = ShoppingCartApp.cartContentsHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getShoppingCartContents (contents        );
            } finally {
                _releaseReply ($in);
            }
  } // getShoppingCartContents

  public void addToShoppingCart (String productId, int amount)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addToShoppingCart", true);
                $out.write_string (productId);
                $out.write_long (amount);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addToShoppingCart (productId, amount        );
            } finally {
                _releaseReply ($in);
            }
  } // addToShoppingCart

  public void updateAmount (String productId, int new_amount)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateAmount", true);
                $out.write_string (productId);
                $out.write_long (new_amount);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updateAmount (productId, new_amount        );
            } finally {
                _releaseReply ($in);
            }
  } // updateAmount

  public void clearShoppingCart ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("clearShoppingCart", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                clearShoppingCart (        );
            } finally {
                _releaseReply ($in);
            }
  } // clearShoppingCart

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ShoppingCartApp/ShoppingCart:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ShoppingCartStub
