package ShoppingCartApp;


/**
* ShoppingCartApp/cartContentsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

abstract public class cartContentsHelper
{
  private static String  _id = "IDL:ShoppingCartApp/cartContents:1.0";

  public static void insert (org.omg.CORBA.Any a, ShoppingCartApp.ShoppingCartEntry[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ShoppingCartApp.ShoppingCartEntry[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ShoppingCartApp.ShoppingCartEntryHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ShoppingCartApp.cartContentsHelper.id (), "cartContents", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ShoppingCartApp.ShoppingCartEntry[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ShoppingCartApp.ShoppingCartEntry value[] = null;
    int _len0 = istream.read_long ();
    value = new ShoppingCartApp.ShoppingCartEntry[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ShoppingCartApp.ShoppingCartEntryHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ShoppingCartApp.ShoppingCartEntry[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ShoppingCartApp.ShoppingCartEntryHelper.write (ostream, value[_i0]);
  }

}
