package ShoppingCartApp;


/**
* ShoppingCartApp/cartContentsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

public final class cartContentsHolder implements org.omg.CORBA.portable.Streamable
{
  public ShoppingCartApp.ShoppingCartEntry value[] = null;

  public cartContentsHolder ()
  {
  }

  public cartContentsHolder (ShoppingCartApp.ShoppingCartEntry[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ShoppingCartApp.cartContentsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ShoppingCartApp.cartContentsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ShoppingCartApp.cartContentsHelper.type ();
  }

}
