package ShoppingCartApp;


/**
* ShoppingCartApp/ShoppingCartHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

abstract public class ShoppingCartHelper
{
  private static String  _id = "IDL:ShoppingCartApp/ShoppingCart:1.0";

  public static void insert (org.omg.CORBA.Any a, ShoppingCartApp.ShoppingCart that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ShoppingCartApp.ShoppingCart extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ShoppingCartApp.ShoppingCartHelper.id (), "ShoppingCart");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ShoppingCartApp.ShoppingCart read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ShoppingCartStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ShoppingCartApp.ShoppingCart value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ShoppingCartApp.ShoppingCart narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ShoppingCartApp.ShoppingCart)
      return (ShoppingCartApp.ShoppingCart)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ShoppingCartApp._ShoppingCartStub stub = new ShoppingCartApp._ShoppingCartStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ShoppingCartApp.ShoppingCart unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ShoppingCartApp.ShoppingCart)
      return (ShoppingCartApp.ShoppingCart)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ShoppingCartApp._ShoppingCartStub stub = new ShoppingCartApp._ShoppingCartStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
