package ShoppingCartApp;


/**
* ShoppingCartApp/ShoppingCartEntry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

public final class ShoppingCartEntry implements org.omg.CORBA.portable.IDLEntity
{
  public String productID = null;
  public int amount = (int)0;

  public ShoppingCartEntry ()
  {
  } // ctor

  public ShoppingCartEntry (String _productID, int _amount)
  {
    productID = _productID;
    amount = _amount;
  } // ctor

} // class ShoppingCartEntry
