package ShoppingCartApp;

/**
* ShoppingCartApp/ShoppingCartHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

public final class ShoppingCartHolder implements org.omg.CORBA.portable.Streamable
{
  public ShoppingCartApp.ShoppingCart value = null;

  public ShoppingCartHolder ()
  {
  }

  public ShoppingCartHolder (ShoppingCartApp.ShoppingCart initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ShoppingCartApp.ShoppingCartHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ShoppingCartApp.ShoppingCartHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ShoppingCartApp.ShoppingCartHelper.type ();
  }

}
