package ShoppingCartApp;


/**
* ShoppingCartApp/ShoppingCart.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

public interface ShoppingCart extends ShoppingCartOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ShoppingCart
