package ShoppingCartApp;


/**
* ShoppingCartApp/ShoppingCartOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShoppingCart.idl
* Donnerstag, 28. April 2016 18:30 Uhr MESZ
*/

public interface ShoppingCartOperations 
{
  void getShoppingCartContents (ShoppingCartApp.cartContentsHolder contents);
  void addToShoppingCart (String productId, int amount);
  void updateAmount (String productId, int new_amount);
  void clearShoppingCart ();
} // interface ShoppingCartOperations
