# Python stubs generated by omniidl from ShoppingCart.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "ShoppingCartApp"
#
__name__ = "ShoppingCartApp"
_0_ShoppingCartApp = omniORB.openModule("ShoppingCartApp", r"ShoppingCart.idl")
_0_ShoppingCartApp__POA = omniORB.openModule("ShoppingCartApp__POA", r"ShoppingCart.idl")


# struct ShoppingCartEntry
_0_ShoppingCartApp.ShoppingCartEntry = omniORB.newEmptyClass()
class ShoppingCartEntry (omniORB.StructBase):
    _NP_RepositoryId = "IDL:ShoppingCartApp/ShoppingCartEntry:1.0"

    def __init__(self, productID, amount):
        self.productID = productID
        self.amount = amount

_0_ShoppingCartApp.ShoppingCartEntry = ShoppingCartEntry
_0_ShoppingCartApp._d_ShoppingCartEntry  = (omniORB.tcInternal.tv_struct, ShoppingCartEntry, ShoppingCartEntry._NP_RepositoryId, "ShoppingCartEntry", "productID", (omniORB.tcInternal.tv_string,0), "amount", omniORB.tcInternal.tv_long)
_0_ShoppingCartApp._tc_ShoppingCartEntry = omniORB.tcInternal.createTypeCode(_0_ShoppingCartApp._d_ShoppingCartEntry)
omniORB.registerType(ShoppingCartEntry._NP_RepositoryId, _0_ShoppingCartApp._d_ShoppingCartEntry, _0_ShoppingCartApp._tc_ShoppingCartEntry)
del ShoppingCartEntry

# typedef ... cartContents
class cartContents:
    _NP_RepositoryId = "IDL:ShoppingCartApp/cartContents:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_ShoppingCartApp.cartContents = cartContents
_0_ShoppingCartApp._d_cartContents  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ShoppingCartApp/ShoppingCartEntry:1.0"], 0)
_0_ShoppingCartApp._ad_cartContents = (omniORB.tcInternal.tv_alias, cartContents._NP_RepositoryId, "cartContents", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:ShoppingCartApp/ShoppingCartEntry:1.0"], 0))
_0_ShoppingCartApp._tc_cartContents = omniORB.tcInternal.createTypeCode(_0_ShoppingCartApp._ad_cartContents)
omniORB.registerType(cartContents._NP_RepositoryId, _0_ShoppingCartApp._ad_cartContents, _0_ShoppingCartApp._tc_cartContents)
del cartContents

# interface ShoppingCart
_0_ShoppingCartApp._d_ShoppingCart = (omniORB.tcInternal.tv_objref, "IDL:ShoppingCartApp/ShoppingCart:1.0", "ShoppingCart")
omniORB.typeMapping["IDL:ShoppingCartApp/ShoppingCart:1.0"] = _0_ShoppingCartApp._d_ShoppingCart
_0_ShoppingCartApp.ShoppingCart = omniORB.newEmptyClass()
class ShoppingCart :
    _NP_RepositoryId = _0_ShoppingCartApp._d_ShoppingCart[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ShoppingCartApp.ShoppingCart = ShoppingCart
_0_ShoppingCartApp._tc_ShoppingCart = omniORB.tcInternal.createTypeCode(_0_ShoppingCartApp._d_ShoppingCart)
omniORB.registerType(ShoppingCart._NP_RepositoryId, _0_ShoppingCartApp._d_ShoppingCart, _0_ShoppingCartApp._tc_ShoppingCart)

# ShoppingCart operations and attributes
ShoppingCart._d_getShoppingCartContents = ((), (omniORB.typeMapping["IDL:ShoppingCartApp/cartContents:1.0"], ), None)
ShoppingCart._d_addToShoppingCart = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), None)
ShoppingCart._d_updateAmount = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), None)
ShoppingCart._d_clearShoppingCart = ((), (), None)

# ShoppingCart object reference
class _objref_ShoppingCart (CORBA.Object):
    _NP_RepositoryId = ShoppingCart._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def getShoppingCartContents(self, *args):
        return self._obj.invoke("getShoppingCartContents", _0_ShoppingCartApp.ShoppingCart._d_getShoppingCartContents, args)

    def addToShoppingCart(self, *args):
        return self._obj.invoke("addToShoppingCart", _0_ShoppingCartApp.ShoppingCart._d_addToShoppingCart, args)

    def updateAmount(self, *args):
        return self._obj.invoke("updateAmount", _0_ShoppingCartApp.ShoppingCart._d_updateAmount, args)

    def clearShoppingCart(self, *args):
        return self._obj.invoke("clearShoppingCart", _0_ShoppingCartApp.ShoppingCart._d_clearShoppingCart, args)

omniORB.registerObjref(ShoppingCart._NP_RepositoryId, _objref_ShoppingCart)
_0_ShoppingCartApp._objref_ShoppingCart = _objref_ShoppingCart
del ShoppingCart, _objref_ShoppingCart

# ShoppingCart skeleton
__name__ = "ShoppingCartApp__POA"
class ShoppingCart (PortableServer.Servant):
    _NP_RepositoryId = _0_ShoppingCartApp.ShoppingCart._NP_RepositoryId


    _omni_op_d = {"getShoppingCartContents": _0_ShoppingCartApp.ShoppingCart._d_getShoppingCartContents, "addToShoppingCart": _0_ShoppingCartApp.ShoppingCart._d_addToShoppingCart, "updateAmount": _0_ShoppingCartApp.ShoppingCart._d_updateAmount, "clearShoppingCart": _0_ShoppingCartApp.ShoppingCart._d_clearShoppingCart}

ShoppingCart._omni_skeleton = ShoppingCart
_0_ShoppingCartApp__POA.ShoppingCart = ShoppingCart
omniORB.registerSkeleton(ShoppingCart._NP_RepositoryId, ShoppingCart)
del ShoppingCart
__name__ = "ShoppingCartApp"

#
# End of module "ShoppingCartApp"
#
__name__ = "ShoppingCart_idl"

_exported_modules = ( "ShoppingCartApp", )

# The end.
