# DO NOT EDIT THIS FILE!
#
# Python module ShoppingCartApp generated by omniidl

import omniORB
omniORB.updateModule("ShoppingCartApp")

# ** 1. Stub files contributing to this module
import ShoppingCart_idl

# ** 2. Sub-modules

# ** 3. End
